export type RankingOfferData = {
    imgSrc: any;
    productName: string;
    soldNumber: number;
    rotation: number;
}

export const rankingOffers: RankingOfferData[] = [
    {
      imgSrc: 'sciezka/do/obrazka1.jpg',
      productName: 'Produkt 1',
      soldNumber: 100,
      rotation: 45,
    },
    {
      imgSrc: 'sciezka/do/obrazka2.jpg',
      productName: 'Produkt 2',
      soldNumber: 75,
      rotation: 30,
    },
    {
      imgSrc: 'sciezka/do/obrazka3.jpg',
      productName: 'Produkt 3',
      soldNumber: 120,
      rotation: 60,
    },
    {
      imgSrc: 'sciezka/do/obrazka4.jpg',
      productName: 'Produkt 4',
      soldNumber: 90,
      rotation: 75,
    },
    {
      imgSrc: 'sciezka/do/obrazka5.jpg',
      productName: 'Produkt 5',
      soldNumber: 150,
      rotation: 15,
    },
    {
      imgSrc: 'sciezka/do/obrazka6.jpg',
      productName: 'Produkt 6',
      soldNumber: 80,
      rotation: 90,
    },
    {
      imgSrc: 'sciezka/do/obrazka7.jpg',
      productName: 'Produkt 7',
      soldNumber: 110,
      rotation: 45,
    },
    {
      imgSrc: 'sciezka/do/obrazka8.jpg',
      productName: 'Produkt 8',
      soldNumber: 130,
      rotation: 30,
    },
    {
      imgSrc: 'sciezka/do/obrazka9.jpg',
      productName: 'Produkt 9',
      soldNumber: 70,
      rotation: 60,
    },
    {
      imgSrc: 'sciezka/do/obrazka10.jpg',
      productName: 'Produkt 10',
      soldNumber: 95,
      rotation: 80,
    },
    {
      imgSrc: 'sciezka/do/obrazka11.jpg',
      productName: 'Produkt 11',
      soldNumber: 120,
      rotation: 45,
    },
    {
      imgSrc: 'sciezka/do/obrazka12.jpg',
      productName: 'Produkt 12',
      soldNumber: 85,
      rotation: 30,
    },
    {
      imgSrc: 'sciezka/do/obrazka13.jpg',
      productName: 'Produkt 13',
      soldNumber: 100,
      rotation: 60,
    },
    {
      imgSrc: 'sciezka/do/obrazka14.jpg',
      productName: 'Produkt 14',
      soldNumber: 110,
      rotation: 75,
    },
    {
      imgSrc: 'sciezka/do/obrazka15.jpg',
      productName: 'Produkt 15',
      soldNumber: 140,
      rotation: 15,
    },
    {
      imgSrc: 'sciezka/do/obrazka16.jpg',
      productName: 'Produkt 16',
      soldNumber: 75,
      rotation: 90,
    },
    {
      imgSrc: 'sciezka/do/obrazka17.jpg',
      productName: 'Produkt 17',
      soldNumber: 105,
      rotation: 45,
    },
    {
      imgSrc: 'sciezka/do/obrazka18.jpg',
      productName: 'Produkt 18',
      soldNumber: 125,
      rotation: 30,
    },
    {
      imgSrc: 'sciezka/do/obrazka19.jpg',
      productName: 'Produkt 19',
      soldNumber: 65,
      rotation: 60,
    },
    {
      imgSrc: 'sciezka/do/obrazka20.jpg',
      productName: 'Produkt 20',
      soldNumber: 88,
      rotation: 80,
    },
    {
        imgSrc: 'sciezka/do/obrazka1.jpg',
        productName: 'Produkt 1',
        soldNumber: 100,
        rotation: 45,
      },
      {
        imgSrc: 'sciezka/do/obrazka2.jpg',
        productName: 'Produkt 2',
        soldNumber: 75,
        rotation: 30,
      },
      {
        imgSrc: 'sciezka/do/obrazka3.jpg',
        productName: 'Produkt 3',
        soldNumber: 120,
        rotation: 60,
      },
      {
        imgSrc: 'sciezka/do/obrazka4.jpg',
        productName: 'Produkt 4',
        soldNumber: 90,
        rotation: 75,
      },
      {
        imgSrc: 'sciezka/do/obrazka5.jpg',
        productName: 'Produkt 5',
        soldNumber: 150,
        rotation: 15,
      },
      {
        imgSrc: 'sciezka/do/obrazka6.jpg',
        productName: 'Produkt 6',
        soldNumber: 80,
        rotation: 90,
      },
      {
        imgSrc: 'sciezka/do/obrazka7.jpg',
        productName: 'Produkt 7',
        soldNumber: 110,
        rotation: 45,
      },
      {
        imgSrc: 'sciezka/do/obrazka8.jpg',
        productName: 'Produkt 8',
        soldNumber: 130,
        rotation: 30,
      },
      {
        imgSrc: 'sciezka/do/obrazka9.jpg',
        productName: 'Produkt 9',
        soldNumber: 70,
        rotation: 60,
      },
      {
        imgSrc: 'sciezka/do/obrazka10.jpg',
        productName: 'Produkt 10',
        soldNumber: 95,
        rotation: 80,
      },
      {
        imgSrc: 'sciezka/do/obrazka11.jpg',
        productName: 'Produkt 11',
        soldNumber: 120,
        rotation: 45,
      },
      {
        imgSrc: 'sciezka/do/obrazka12.jpg',
        productName: 'Produkt 12',
        soldNumber: 85,
        rotation: 30,
      },
      {
        imgSrc: 'sciezka/do/obrazka13.jpg',
        productName: 'Produkt 13',
        soldNumber: 100,
        rotation: 60,
      },
      {
        imgSrc: 'sciezka/do/obrazka14.jpg',
        productName: 'Produkt 14',
        soldNumber: 110,
        rotation: 75,
      },
      {
        imgSrc: 'sciezka/do/obrazka15.jpg',
        productName: 'Produkt 15',
        soldNumber: 140,
        rotation: 15,
      },
      {
        imgSrc: 'sciezka/do/obrazka16.jpg',
        productName: 'Produkt 16',
        soldNumber: 75,
        rotation: 90,
      },
      {
        imgSrc: 'sciezka/do/obrazka17.jpg',
        productName: 'Produkt 17',
        soldNumber: 105,
        rotation: 45,
      },
      {
        imgSrc: 'sciezka/do/obrazka18.jpg',
        productName: 'Produkt 18',
        soldNumber: 125,
        rotation: 30,
      },
      {
        imgSrc: 'sciezka/do/obrazka19.jpg',
        productName: 'Produkt 19',
        soldNumber: 65,
        rotation: 60,
      },
      {
        imgSrc: 'sciezka/do/obrazka20.jpg',
        productName: 'Produkt 20',
        soldNumber: 88,
        rotation: 80,
      },
      {
        imgSrc: 'sciezka/do/obrazka1.jpg',
        productName: 'Produkt 1',
        soldNumber: 100,
        rotation: 45,
      },
      {
        imgSrc: 'sciezka/do/obrazka2.jpg',
        productName: 'Produkt 2',
        soldNumber: 75,
        rotation: 30,
      },
      {
        imgSrc: 'sciezka/do/obrazka3.jpg',
        productName: 'Produkt 3',
        soldNumber: 120,
        rotation: 60,
      },
      {
        imgSrc: 'sciezka/do/obrazka4.jpg',
        productName: 'Produkt 4',
        soldNumber: 90,
        rotation: 75,
      },
      {
        imgSrc: 'sciezka/do/obrazka5.jpg',
        productName: 'Produkt 5',
        soldNumber: 150,
        rotation: 15,
      },
      {
        imgSrc: 'sciezka/do/obrazka6.jpg',
        productName: 'Produkt 6',
        soldNumber: 80,
        rotation: 90,
      },
      {
        imgSrc: 'sciezka/do/obrazka7.jpg',
        productName: 'Produkt 7',
        soldNumber: 110,
        rotation: 45,
      },
      {
        imgSrc: 'sciezka/do/obrazka8.jpg',
        productName: 'Produkt 8',
        soldNumber: 130,
        rotation: 30,
      },
      {
        imgSrc: 'sciezka/do/obrazka9.jpg',
        productName: 'Produkt 9',
        soldNumber: 70,
        rotation: 60,
      },
      {
        imgSrc: 'sciezka/do/obrazka10.jpg',
        productName: 'Produkt 10',
        soldNumber: 95,
        rotation: 80,
      },
      {
        imgSrc: 'sciezka/do/obrazka11.jpg',
        productName: 'Produkt 11',
        soldNumber: 120,
        rotation: 45,
      },
      {
        imgSrc: 'sciezka/do/obrazka12.jpg',
        productName: 'Produkt 12',
        soldNumber: 85,
        rotation: 30,
      },
      {
        imgSrc: 'sciezka/do/obrazka13.jpg',
        productName: 'Produkt 13',
        soldNumber: 100,
        rotation: 60,
      },
      {
        imgSrc: 'sciezka/do/obrazka14.jpg',
        productName: 'Produkt 14',
        soldNumber: 110,
        rotation: 75,
      },
      {
        imgSrc: 'sciezka/do/obrazka15.jpg',
        productName: 'Produkt 15',
        soldNumber: 140,
        rotation: 15,
      },
      {
        imgSrc: 'sciezka/do/obrazka16.jpg',
        productName: 'Produkt 16',
        soldNumber: 75,
        rotation: 90,
      },
      {
        imgSrc: 'sciezka/do/obrazka17.jpg',
        productName: 'Produkt 17',
        soldNumber: 105,
        rotation: 45,
      },
      {
        imgSrc: 'sciezka/do/obrazka18.jpg',
        productName: 'Produkt 18',
        soldNumber: 125,
        rotation: 30,
      },
      {
        imgSrc: 'sciezka/do/obrazka19.jpg',
        productName: 'Produkt 19',
        soldNumber: 65,
        rotation: 60,
      },
      {
        imgSrc: 'sciezka/do/obrazka20.jpg',
        productName: 'Produkt 20',
        soldNumber: 88,
        rotation: 80,
      },
  ];
  